CLASS LHC_ZZCIR_CIT_ADM_TABLE_1036 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZzcirCitAdmTable1036
        RESULT result.
ENDCLASS.

CLASS LHC_ZZCIR_CIT_ADM_TABLE_1036 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
